### ISSUE TITLE
Applying RoIDE to longitudinal differential expression dataset with no repeated measures

### ISSUE THREAD

**Issue by tubenn** [elolab/RolDE#1]
Dear Elo Lab,

I am with great enthusiasm trying to apply your RoIDE approach to a dataset with 20 timepoints and two conditions. For each timepoint, I have differential expression data for a number (>10) of independent samples, which all only have been measured once. Hence, there are no replicates or repeats and all samples are individual and unique.
All entries in the "Replicate/Individual" column are therefore unique (the numerical ID run from 1 to the total number of samples). Is it correct that this design is incompatible with RoIDE or do you have any advice to the design matrix?

Any input will be greatly appreciated and thank you for your time.

**Comment by tsvali** [comment]
Dear Professor Bennike,

Thank you for your interest in our RolDE method! If I understood correctly, you have measurements from different individuals within a condition at each timepoint? If this is the case, I am afraid you are correct, this design is incompatible with RolDE at the moment. RolDE requires repeated measurements from the same individuals at multiple timepoints (bare minimum is three measurements / timepoints) within a condition to determine longitudinal different expression between the conditions. In your case, would it be appropriate to determine differential expression between the conditions at each timepoint separately? For this purpose, our Reproducibility Optimized Test Statistic (ROTS) could be a suitable tool (https://bioconductor.org/packages/release/bioc/html/ROTS.html). The results from the different timepoints could be compared or combined in various ways (e.g. with a meta-analysis of p-values using the metap package) to determine common interesting proteins across the timepoints. 

Best Regards,
Tommi Välikangas
